name: Docker Image

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

env:
  NAME: smortezah/cryfa
  TAG: 20.04

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.NAME}}:${{env.TAG}}

    - name: Push the Docker image
      run: |
        docker push ${{env.NAME}}:${{env.TAG}}
        docker push ${{env.NAME}}:latest
        